User.create(first_name: 'arye', last_name: 'eidelman', email: 'aryedov.e@gmail.com', password: 'password')
User.create(first_name: 'zalmi', last_name: 'eidelman', email: 'zalmi726@gmail.com', password: 'password')
User.create(first_name: 'hb y', last_name: 'dddddddd', email: 'fhbtdr@gmail.com', password: 'password')
User.create(first_name: 'dfddscg', last_name: 'apple', email: 'asdfghjkl.643v4@gmail.com', password: 'password')
User.create(first_name: 'john', last_name: 'green', email: 'rfvtgbyhn@gmail.com', password: 'password')
